on: [push]
jobs:
  runs-on: ubuntu-latest
  matrix:
    strategy:
      matrix:
        version: [16, 18]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@v2
      - id: create-release-presets
        shell: bash
        run: |
          yarn install --network-concurrency 1
